import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Index.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description"
              content="Generated by create next app"/>
        <link rel="icon"
              href="/favicon.ico"/>
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>

        <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
          Button
        </button>
      </main>


    </div>
  )
}

export default Home
